// ──────────────────────────────────────────────
// OCCUPATIONS DATA (with AI reason explanation)
// ──────────────────────────────────────────────
export const OCCUPATIONS = [
  // Savdo va xizmat ko'rsatish
  { name: "Savdo xodimlari va sotuvchilar", sector: "Savdo va xizmat", ai: 6, jobs: 1450000, pay: 3200000, outlook: "3% (O'rtacha)", edu: "O'rta yoki undan past", desc: "Chakana va ulgurji savdo bo'yicha sotuvchilar, kassirlar va do'kon menejerlari.", reason: "Kassalar va mahsulot tavsiyalari tobora avtomatlashmoqda. AI tahlil tizimlari va online savdo platformalari ushbu kasbni siqib chiqarmoqda — ayniqsa oddiy kassirlik va buyurtma qabul qilish vazifalari xavf ostida." },
  { name: "Restoran va oshxona xodimlari", sector: "Savdo va xizmat", ai: 4, jobs: 450000, pay: 2800000, outlook: "8% (Juda tez)", edu: "Rasmiy ta'lim talab etilmaydi", desc: "Oshpazlar, ofitsiantlar, menejerlar.", reason: "Ovqat tayyorlash va servis ko'rsatishda insoniy aloqa hali muhim, ammo avtomat buyurtma terminallari va yetkazib berish robotlari ayrim vazifalarni egallaydi. Ijodiy oshpazlik xavf ostida emas." },
  { name: "Uy-joy va kommunal xizmatlar", sector: "Savdo va xizmat", ai: 2, jobs: 220000, pay: 2500000, outlook: "1% (Sekin)", edu: "O'rta", desc: "Kommunal xizmatlar.", reason: "Jismoniy ta'mirlash, uy xizmati va aholini boshqarish asosan qo'l mehnatini talab qiladi. AI sensorlar kichik o'zgarishlarni kuzatsa ham, asosiy ish o'rinlari barqaror." },
  { name: "Ko'chmas mulk agentlari", sector: "Savdo va xizmat", ai: 5, jobs: 45000, pay: 4800000, outlook: "5% (Tez)", edu: "O'rta", desc: "Rieltor va mulk boshqaruvchilari.", reason: "Narx bashorat qilish va mulk qidirishda AI activlashmoqda. Ammo savdoni yakunlash, muzokaralar va ishonch qurish hali inson ko'magi talab qiladi." },
  { name: "Mehmonxona xodimlari", sector: "Savdo va xizmat", ai: 3, jobs: 120000, pay: 3000000, outlook: "10% (Portlash)", edu: "O'rta", desc: "Turizm boshqaruvi va room service.", reason: "Mehmon xizmati, kayfiyatni anglash va shaxsiy bo'lgan muloqot — bular AI uchun qiyin. Ijtmoiy va mehribon xizmat turizm daromadini saqlab qoladi." },
  { name: "Sartarosh va go'zallik xodimlari", sector: "Savdo va xizmat", ai: 1, jobs: 180000, pay: 3500000, outlook: "6% (Tez)", edu: "O'rta maxsus", desc: "Sartaroshxona xizmatlari.", reason: "Jismoniy mahorat, estetik sezgi va individual muloqot asosida ishlaydi. Bunday kasblarni avtomatlashtirish texnik jihatdan cheklangan va ijtimoiy jihatdan qabul qilinmaydi." },
  { name: "Turizm operatorlari va gidlar", sector: "Savdo va xizmat", ai: 4, jobs: 28000, pay: 4000000, outlook: "12% (Portlash)", edu: "Oliy", desc: "Gidlar xizmati.", reason: "Marshrut rejalash va axborot berish AI tomonidan qisman amalga oshirilishi mumkin, lekin jonli gid, mahalliy bilim va hissiyot bilan gaplashish saqlanib qoladi." },
  { name: "Ta'mirlash xodimlari", sector: "Savdo va xizmat", ai: 2, jobs: 110000, pay: 2800000, outlook: "2% (Sekin)", edu: "O'rta", desc: "Texnik xizmat ko'rsatish.", reason: "Uy va uskunalarni ta'mirlash nozik ko'nikma va ixtisoslik talab qiladi. Robototexnika hali bunday nomutanosib vazifalarni bajara olmaydi." },

  // Ta'lim va ilm-fan
  { name: "Umumta'lim o'qituvchilari", sector: "Ta'lim va Ilm-fan", ai: 5, jobs: 1100000, pay: 3800000, outlook: "4% (O'rtacha)", edu: "Oliy (bakalavr+)", desc: "Maktab va kollejlardagi o'qituvchilar.", reason: "Dars rejalashtirish va testlarni tekshirish avtomatlashishi mumkin, lekin tarbiyaviy ta'sir, motivatsiya va inson rishtasi hali mashinaga o'tmaydi. O'rta ta'sir darajasida." },
  { name: "O'yin va sport murabbiylar", sector: "Ta'lim va Ilm-fan", ai: 2, jobs: 60000, pay: 3200000, outlook: "5% (Tez)", edu: "Oliy", desc: "Sport kompleks murabbiylari.", reason: "Jismoniy treninglar, ruhiy ko'mak va real-time qaror qabul qilish — bular AI egollay olmaydi. Sport murabbiyligi juda past xatarli kasb." },

  // Qishloq xo'jaligi
  { name: "Dehqon va fermerlar", sector: "Qishloq xo'jaligi", ai: 2, jobs: 3600000, pay: 2200000, outlook: "1% (Sekin)", edu: "Rasmiy ta'lim talab etilmaydi", desc: "Yer ishlash, ekin ekish va hosil yig'ish.", reason: "Qishloq xo'jaligida drone va sensor texnologiyalari paydo bo'lmoqda, ammo O'zbekistondagi kichik fermer xo'jaliklari hali an'anaviy usullarga suyanaveradi. Avtomatlashtirish sekin." },
  { name: "Chorvachilik mutaxassislari", sector: "Qishloq xo'jaligi", ai: 2, jobs: 1200000, pay: 2000000, outlook: "2% (Sekin)", edu: "Rasmiy ta'lim talab etilmaydi", desc: "Qoramol, qo'y, echki va parrandachilik.", reason: "Hayvon parvarishi, kasallik aniqlash va nazorat — bular hali tirik ko'z va tajriba talab qiladi. AI faqat monitoring qo'shimcha sifatida ishlaydi." },
  { name: "Bog'bon va uzumchilar", sector: "Qishloq xo'jaligi", ai: 1, jobs: 550000, pay: 2100000, outlook: "3% (O'rtacha)", edu: "Rasmiy ta'lim talab etilmaydi", desc: "Meva-sabzavot, uzum xodimlari.", reason: "Pishiqlik aniqlash, nozik yig'ish va joylashuvni bilish — bular mashina uchun murakkab. Bog'bonlik va meva-sabzavotchilik AI xavfiga juda chidamli." },
  { name: "Paxta terish va qayta ishlash", sector: "Qishloq xo'jaligi", ai: 2, jobs: 600000, pay: 1800000, outlook: "-4% (Kamayish)", edu: "Rasmiy ta'lim talab etilmaydi", desc: "Paxta yig'ish va qayta ishlash.", reason: "Paxta yig'ish mashinalari mavjud, ammo O'zbekiston qishloqlarida keng tarqalishi sekin ketmoqda. Xavf past, lekin mehnat tanqisligi ehtimol saqlanib qoladi." },
  { name: "Qishloq xo'jalik texnika operatorlari", sector: "Qishloq xo'jaligi", ai: 3, jobs: 180000, pay: 3000000, outlook: "0% (Barqaror)", edu: "O'rta maxsus", desc: "Traktor va kombayn boshqaruvchilari.", reason: "Avtonom traktorlar sinovdan o'tmoqda, lekin hali keng qabul qilinmaydi. GPS-yunaltirish qisman joriy etilgan, shuning uchun o'rtacha xavf darajasi." },
  { name: "Irrigatsiya mutaxassislari", sector: "Qishloq xo'jaligi", ai: 4, jobs: 55000, pay: 3500000, outlook: "2% (Sekin)", edu: "Oliy", desc: "Sug'orish tizimi mutaxassislari.", reason: "Smart irrigatsiya IoT sensorlari va AI modellari bilan boyitilyapti. Ammo tizimni loyihalash va ta'mirlash hali ixtisoslik talab qiladi." },
  { name: "Agronomlar va tuproqshunos", sector: "Qishloq xo'jaligi", ai: 5, jobs: 35000, pay: 4000000, outlook: "3% (O'rtacha)", edu: "Oliy", desc: "Ekin rejalari va agro-maslahat.", reason: "AI tuproq tahlili va hosildorlik bashoratida faol qo'llanilmoqda. Maslahat va strategiya qismi hali inson ishtiroki talab qiladi — o'rtacha ta'sir." },
  { name: "Veterinar shifokorlar", sector: "Qishloq xo'jaligi", ai: 3, jobs: 25000, pay: 3800000, outlook: "4% (O'rtacha)", edu: "Oliy", desc: "Chorvachilik va hayvonlar salomatligi.", reason: "Laboratoriya tahlil va diagnostika qisman avtomatlashadi, lekin hayvon muolajasi va operatsiya hali mutaxassis talab qiladi." },

  // Tibbiyot va ijtimoiy soha
  { name: "Shifokorlar va tibbiyot xodimlari", sector: "Tibbiyot va Ijtimoiy Himoya", ai: 6, jobs: 750000, pay: 5500000, outlook: "6% (Tez)", edu: "Oliy (tibbiyot instituti)", desc: "Shifokorlar, jarrohlar va hamshiralar.", reason: "Radiologiya va laborator tashxisda AI kuchi oshib bormoqda. Ammo bemor bilan inson munosabati, operatsiya va ko'p omilli klinik fikrlash hali inson ishtiroki talab qiladi." },
  { name: "Psixolog va ijtimoiy xodimlar", sector: "Tibbiyot va Ijtimoiy Himoya", ai: 3, jobs: 25000, pay: 3500000, outlook: "7% (Juda tez)", edu: "Oliy", desc: "Ijtimoiy yordam.", reason: "Empathy, insoniy aloqa va hissiy ko'mak — bular AI bajara olmaydi. Psixologik yordam va ijtimoiy ishlar insoniy mavjudliq bilan bevosita bog'liq." },

  // Transport va logistika
  { name: "Haydovchilar va transport xodimlari", sector: "Transport va logistika", ai: 5, jobs: 850000, pay: 3500000, outlook: "2% (Sekin)", edu: "O'rta", desc: "Yuk va yo'lovchi tashish haydovchilari.", reason: "Avtonom transport texnologiyalari rivojlanmoqda, ammo O'zbekiston yo'llari va infratuzilmasida uni qo'llash hali masofada. 5-10 yil ichida xavf oshishi mumkin." },
  { name: "Pochta va kuryer xodimlari", sector: "Transport va logistika", ai: 5, jobs: 85000, pay: 2500000, outlook: "3% (O'rtacha)", edu: "O'rta", desc: "Pochta yetkazuvchisi.", reason: "Drone yetkazib berish va marshrutlash tizimlari kengaymoqda. Shahar ko'chalarida avtomatlashtirish qiyin bo'lsa ham, yirik omborlarda robotlar faollashtirilyapti." },

  // Moliya va boshqaruv
  { name: "Davlat boshqaruvi xodimlari", sector: "Moliya va Davlat Boshqaruvi", ai: 7, jobs: 420000, pay: 4200000, outlook: "-2% (Kamayish)", edu: "Oliy (bakalavr+)", desc: "Hokimliklar, vazirliklar xodimlari.", reason: "Hujjat rasmiylashtirish, ma'lumot kiritish va tartibga solish vazifalari tezda avtomatlashmoqda. E-davlat tizimlari ko'plab ma'muriy rollarni qisqartirmoqda." },
  { name: "Moliya va bank xodimlari", sector: "Moliya va Davlat Boshqaruvi", ai: 8, jobs: 120000, pay: 7500000, outlook: "-3% (Kamayish)", edu: "Oliy (bakalavr+)", desc: "Buxgalterlar, bank xodimlari.", reason: "Kredit baholash, hisobot tuzish va moliyaviy tahlil AI tomonidan jadal egallab borilyapti. Raqamli banking standart operatsiyalarni qisqartirmoqda — yuqori xavf." },
  { name: "Advokat va huquqshunos", sector: "Moliya va Davlat Boshqaruvi", ai: 7, jobs: 35000, pay: 8000000, outlook: "1% (Sekin)", edu: "Oliy (magistr)", desc: "Sud ishlari va konsultant.", reason: "Shartnomalar tahlili, qonuniy tadqiqot va hujjat tuzish AI orqali tezlashmoqda. Sudlava strategiya va muzokaralar hali inson mutaxassisligini talab qiladi." },

  // Qurilish va arxitektura
  { name: "Qurilish ishchilari", sector: "Qurilish va Arxitektura", ai: 2, jobs: 1100000, pay: 3200000, outlook: "5% (Tez)", edu: "Rasmiy ta'lim talab etilmaydi", desc: "Bino va inshootlar qurish.", reason: "Qurilish jismoniy ko'nikma, moslashuvchanlik va noaniq muhitni talab qiladi — robotlar uchun hali qiyin. Mashinasi kam, shuning uchun xavf past." },
  { name: "Elektr va santexnik ustalar", sector: "Qurilish va Arxitektura", ai: 2, jobs: 240000, pay: 3500000, outlook: "3% (O'rtacha)", edu: "O'rta maxsus", desc: "Ichki qurilish ta'mirlari.", reason: "Har bir uy va bino turlicha — bu avtomatlashtirishni qiyinlashtiradi. O'ziga xos jismoniy ko'nikma va tezkor qaror qabul qilish talab qilinadi." },
  { name: "Arxitektor va loyihachilar", sector: "Qurilish va Arxitektura", ai: 6, jobs: 25000, pay: 6500000, outlook: "2% (Sekin)", edu: "Oliy", desc: "Bino va ko'cha arxitektorlari.", reason: "Generativ dizayn vositalari va BIM modellash AI bilan boyitilyapti. Ijodiy konseptsiya hali inson ishtiroki talab qilsa-da, texnik hujjatlashtirish avtomatlashmoqda." },
  { name: "Kran va og'ir texnika operatorlari", sector: "Qurilish va Arxitektura", ai: 4, jobs: 45000, pay: 4000000, outlook: "1% (Sekin)", edu: "O'rta maxsus", desc: "Og'ir texnika operatorlari.", reason: "Masofadan boshqarish va yarim avtonom kranlar paydo bo'lyapti. Ammo noryeq sharoitdagi qarorlar hali operator tajribasini talab qiladi." },

  // Sanoat va ishlab chiqarish
  { name: "Konchilik ishchilari", sector: "Sanoat va Ishlab Chiqarish", ai: 3, jobs: 110000, pay: 5000000, outlook: "1% (Sekin)", edu: "O'rta maxsus", desc: "Oltin, uran, mis konlari ishchilari.", reason: "Yer osti muhiti xavfli va nomunosib — robot texnologiyalari hali cheklangan. Sensor va monitoring tizimlari qo'shimcha bo'lib ishlaydi." },
  { name: "Metallurgiya xodimlari", sector: "Sanoat va Ishlab Chiqarish", ai: 5, jobs: 140000, pay: 4500000, outlook: "0% (Barqaror)", edu: "O'rta maxsus", desc: "Metallurgiya kombinati ishchilari.", reason: "Katta sanoat korxonalarida avtomatlashtirish sekin amalga oshirilyapti. Metal qayta ishlash liniyalari robotlashtirilyapti, ammo nazorat va texnik xizmat inson talab qiladi." },
  { name: "Kimyo sanoati xodimlari", sector: "Sanoat va Ishlab Chiqarish", ai: 6, jobs: 95000, pay: 4800000, outlook: "2% (Sekin)", edu: "Oliy", desc: "O'g'itlar va zavod ishchilari.", reason: "Kimyoviy jarayonlarni boshqarish va optimallash AI va sensorlar orqali tobora avtomatlashmoqda. Xavfli muhit robotlashtirishni tezlashtiryapti." },
  { name: "Neft-gaz mutaxassislari", sector: "Sanoat va Ishlab Chiqarish", ai: 5, jobs: 85000, pay: 7000000, outlook: "1% (Sekin)", edu: "Oliy", desc: "Neft va gaz qazib olish.", reason: "Seysmik tahlil va qazish rejasini optimallashda AI faol qo'llanilmoqda. Ammo joydagi operatsiyalar va texnik xizmat hali mutaxassis talab qiladi." },
  { name: "Avtomobilsozlik (UzAuto)", sector: "Sanoat va Ishlab Chiqarish", ai: 7, jobs: 110000, pay: 5500000, outlook: "3% (O'rtacha)", edu: "O'rta maxsus", desc: "Avtomobil yig'ish va texnik nazorat.", reason: "Yig'ish liniyalari tobora robotlashtirilmoqda. UzAuto ham avtomatlashtirish yo'lini tutmoqda — takroriy konveyer vazifalari yuqori xatarda." },
  { name: "Energetika xodimlari", sector: "Sanoat va Ishlab Chiqarish", ai: 6, jobs: 90000, pay: 5000000, outlook: "2% (Sekin)", edu: "Oliy", desc: "Elektr stansiyalari boshqaruvchilari.", reason: "Aqlli tarmoq va avtomatik boshqaruv tizimlari kengaymoqda. Yuqori voltage muhitida xavfsizlik qarorlari va favqulodda holat boshqaruvi hali inson talab qiladi." },
  { name: "To'qimachilik ishchilari", sector: "Sanoat va Ishlab Chiqarish", ai: 6, jobs: 450000, pay: 3200000, outlook: "-1% (Kamayish)", edu: "O'rta", desc: "Kiyim va to'qimachilik sanoati.", reason: "Tikuv va to'quv mashinalari jadal robotlashtirilmoqda. O'zbekiston to'qimachilik sanoatida avtomatlashtirishga sarmoya ortib bormoqda — yuqori xavf." },
  { name: "Mashinasozlik ishchilari", sector: "Sanoat va Ishlab Chiqarish", ai: 5, jobs: 180000, pay: 4000000, outlook: "2% (Sekin)", edu: "O'rta maxsus", desc: "Dastgoh va texnika ta'mirlash.", reason: "CNC dastgohlar va robototexnika yig'ish liniyalarini egallayapti. Ammo ta'mirlash, nosozliklarni bartaraf etish va moslashuvchanlik hali inson ko'nikmasi talab qiladi." },
  { name: "Oziq-ovqat sanoati xodimlari", sector: "Sanoat va Ishlab Chiqarish", ai: 4, jobs: 280000, pay: 3000000, outlook: "5% (Tez)", edu: "O'rta", desc: "Oziq-ovqat va konservalar.", reason: "Konservalash va qadoqlash liniyalari avtomatlashmoqda, ammo sifat nazorati va turli mahsulot turlari bilan ishlash hali inson ishtiroki talab qiladi." },
  { name: "Qurilish materiallari ishchilari", sector: "Sanoat va Ishlab Chiqarish", ai: 3, jobs: 190000, pay: 3200000, outlook: "4% (O'rtacha)", edu: "O'rta", desc: "Bino materiallari yig'uvchilar.", reason: "G'isht va sement ishlab chiqarishdagi ba'zi bosqichlar avtomatlashgan, lekin kichik zavodlarda texnologiya kiritish sekin ketmoqda." },
  { name: "Tikuvchilar va charm ishlash", sector: "Sanoat va Ishlab Chiqarish", ai: 5, jobs: 290000, pay: 2500000, outlook: "0% (Barqaror)", edu: "O'rta", desc: "Poyafzal va trikotaj mahsulotlar.", reason: "Avtomatik tikuv mashinalari standart mahsulotlar uchun kengaymoqda. Nozik charm buyumlar va maxsus dizayn hali qo'l mehnatini talab qiladi." },
  { name: "Yengil sanoat texnologlari", sector: "Sanoat va Ishlab Chiqarish", ai: 6, jobs: 35000, pay: 4200000, outlook: "2% (Sekin)", edu: "Oliy", desc: "Sanoat texnik qatorlari menejmenti.", reason: "Ishlab chiqarish jarayonini optimallashtirish, liniyani nazorat qilish va hisobot tuzish AI tizimlari orqali qisqarmoqda." },

  // Axborot texnologiyalari (IT)
  { name: "Telekommunikatsiya xodimlari", sector: "IT va Telekom", ai: 7, jobs: 65000, pay: 6200000, outlook: "0% (Barqaror)", edu: "Oliy", desc: "Mobil va internet provayder.", reason: "Tarmoq monitoringi va nosozlik aniqlash avtomatlashmoqda. Ammo infratuzilmani jismoniy ta'mirlash va murakkab texnik qarorlar hali mutaxassis talab qiladi." },
  { name: "Dasturchilar (Software)", sector: "IT va Telekom", ai: 9, jobs: 25000, pay: 15000000, outlook: "20% (Portlash)", edu: "Oliy", desc: "Web, mobil va backend.", reason: "AI kod yozishni tezlashtiradi, lekin arxitektura, talablar tahlili va innovatsion muammolarni hal qilish yangi dasturchilarni talab qiladi. Bu kasb o'zgaradi, ammo o'smaydi." },
  { name: "IT qo'llab-quvvatlash", sector: "IT va Telekom", ai: 6, jobs: 18000, pay: 5000000, outlook: "8% (Tez)", edu: "O'rta maxsus", desc: "Tech yordam uskunalar.", reason: "1-bosqich yordam va keng tarqalgan nosozliklarni bartaraf etish chatbotlar va otomatlashgan tizimlar tomonidan tobora ko'proq qabul qilinmoqda." },
  { name: "Tizim administratorlari", sector: "IT va Telekom", ai: 7, jobs: 12000, pay: 8000000, outlook: "5% (Tez)", edu: "Oliy", desc: "Server va DevOps boshqaruvchi.", reason: "Bulutli avtomatlashtirish va DevOps vositalari ko'plab server boshqaruv vazifalarini egollamoqda. Yuqori darajadagi strategik qaror va xavfsizlik hali mutaxassis talab qiladi." },
  { name: "Data tahlilchilar", sector: "IT va Telekom", ai: 9, jobs: 8000, pay: 12000000, outlook: "25% (Portlash)", edu: "Oliy", desc: "Big Data tahlili vositalari.", reason: "Ma'lumotlar tahlili AI tomonidan kuchaytirilmoqda, ammo muammo topish, savollar qo'yish va biznes qiymatini tushunish hali chuqur inson ishtiroki talab qiladi." },
  { name: "UX/UI dizaynerlar", sector: "IT va Telekom", ai: 8, jobs: 6000, pay: 10000000, outlook: "15% (Juda tez)", edu: "Oliy", desc: "Dizayn UX interfeys yaratish.", reason: "Generativ AI dizayn prototiplarini yaratadi va testlaydi. Ammo foydalanuvchi tadqiqoti, empatiya va mahsulot strategiyasi hali ijodiy inson ishtiroki talab qiladi." },
  { name: "Kiberxavfsizlik mutaxassislari", sector: "IT va Telekom", ai: 7, jobs: 4500, pay: 14000000, outlook: "30% (Portlash)", edu: "Oliy", desc: "IT xavfsiligi tizimlarini taminlash.", reason: "Xavf monitoringi va anomaliya aniqlash avtomatlashgan, lekin yangi tahdidlarga javob berish va himoya strategiyasini ishlab chiqish kuchli mutaxassislar talab qiladi." },
  { name: "AI/ML mutaxassislari", sector: "IT va Telekom", ai: 10, jobs: 2500, pay: 18000000, outlook: "40% (Portlash)", edu: "Oliy (magistr+)", desc: "AI startuplari uchun ishlab chiquvchilar.", reason: "Bu kasb AI tomonidan emas, balki AI yaratadi. Ammo o'zgartirishni boshqurvchi modellar va avtomatlashtirilgan ML quvurlari ba'zi vazifalarni qo'llagan mutaxassislar bilan jamlashishi mumkin." },

  // Media va san'at
  { name: "Jurnalist va media xodimlari", sector: "Madaniyat va San'at", ai: 7, jobs: 15000, pay: 4500000, outlook: "-5% (Kamayish)", edu: "Oliy", desc: "Yangilik va redaktorlik.", reason: "Ma'lumotga asoslangan yangiliklar va oddiy hisobotlar AI tomonidan yozilyapti. Chuqur tahlil, manbalar bilan ishlash va investigatsiya jurnalistikasi hali inson talab qiladi." },
  { name: "Tarjimonlar", sector: "Madaniyat va San'at", ai: 8, jobs: 12000, pay: 5500000, outlook: "-8% (Tez kamayish)", edu: "Oliy", desc: "Kitob va matnlar tarjimasi.", reason: "Machine translation tez yaxshilanmoqda. Oddiy matnlar uchun AI allaqachon raqobatchi. Texnik, yuridik va adabiy tarjima hali mutaxassis talab qiladi, ammo xavf yuqori." }
]
